name: Android CI
on:
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Change wrapper permissions
      run: chmod +x gradlew

      # Run Tests Build
    - name: Run gradle tests
      run: ./gradlew test

      # Run Build Project
    - name: Build gradle project
      run: ./gradlew build

      # Create APK Debug
    - name: Build apk debug project (APK) - app module
      run: ./gradlew assembleDebug

      # Create APK Release
    - name: Build apk release project (APK) - app  module
      run: ./gradlew assemble
    - name: Build app bundle release (AAB) - app module    
      run: ./gradlew app:bundleRelease
