name: Deploy to App Center

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build APK
      run: ./gradlew assembleDebug
    - name: Upload APK to App Center
      uses: microsoft/appcenter-upload@v2
      with:
        app_name: android
        owner_name: irfan6288
        token: ${{ secrets.APPCENTER_TOKEN }}
        file: app/build/outputs/apk/debug/app-debug.apk
    - name: Deploy APK to App Center
      run: appcenter distribute release --app android --group "test" --release-notes "New features and bug fixes"
