name: Deploy app to App Center

on: [push]

env:
  APP_CENTER_API_TOKEN: ${{ secrets.APP_CENTER_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy app to App Center
      run: |
        # Install App Center Command Line Tool
        npm install -g appcenter-cli

        # Login to App Center
        appcenter login --token ${APP_CENTER_API_TOKEN}

        # Build the APK file
        appcenter builds distribution \
               --token ${APP_CENTER_API_TOKEN} \
               --output ./build \
               --files ./app/release/app-release.apk

        # Deploy the APK file to App Center
        appcenter deploy \
               --token ${APP_CENTER_API_TOKEN} \
               --app "YourOrg/YourApp" \
               --file ./build/app-release.apk
